package tpcorba.serveur;


/**
* serveur/gererCompteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from serveur.idl
* Friday, December 4, 2020 12:40:58 PM WAT
*/

public interface gererCompteOperations 
{
  tpcorba.serveur.gererComptePackage.Compte getCompte (int code);
} // interface gererCompteOperations
