package tpcorba.serveur;

/**
* serveur/gererCompteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from serveur.idl
* Friday, December 4, 2020 12:40:58 PM WAT
*/

public final class gererCompteHolder implements org.omg.CORBA.portable.Streamable
{
  public gererCompte value = null;

  public gererCompteHolder ()
  {
  }

  public gererCompteHolder (gererCompte initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = gererCompteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    gererCompteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return gererCompteHelper.type ();
  }

}
