package tpcorba.serveur.gererComptePackage;


/**
* serveur/gererComptePackage/cptesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from serveur.idl
* Friday, December 4, 2020 12:40:58 PM WAT
*/

public final class cptesHolder implements org.omg.CORBA.portable.Streamable
{
  public tpcorba.serveur.gererComptePackage.Compte value[] = null;

  public cptesHolder ()
  {
  }

  public cptesHolder (tpcorba.serveur.gererComptePackage.Compte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = tpcorba.serveur.gererComptePackage.cptesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    tpcorba.serveur.gererComptePackage.cptesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tpcorba.serveur.gererComptePackage.cptesHelper.type ();
  }

}
