module serveur{
    interface gererCompte{
        struct Compte{
            long code;
            double solde;
        };
        typedef sequence <Compte> cptes;

        Compte getCompte(in long code);

    };
};