package tpcorbaclient.serveur;


/**
* serveur/gererCompteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from serveur.idl
* Friday, December 4, 2020 3:30:59 PM WAT
*/

public interface gererCompteOperations 
{
  tpcorbaclient.serveur.gererComptePackage.Compte getCompte (int code);
} // interface gererCompteOperations
