package tpcorbaclient.serveur;


/**
* serveur/gererCompte.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from serveur.idl
* Friday, December 4, 2020 3:30:59 PM WAT
*/

public interface gererCompte extends gererCompteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface gererCompte
