package tpcorbaclient.serveur;


/**
* serveur/gererCompteHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from serveur.idl
* Friday, December 4, 2020 3:30:59 PM WAT
*/

abstract public class gererCompteHelper
{
  private static String  _id = "IDL:serveur/gererCompte:1.0";

  public static void insert (org.omg.CORBA.Any a, tpcorbaclient.serveur.gererCompte that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static tpcorbaclient.serveur.gererCompte extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (tpcorbaclient.serveur.gererCompteHelper.id (), "gererCompte");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static tpcorbaclient.serveur.gererCompte read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_gererCompteStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, tpcorbaclient.serveur.gererCompte value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static tpcorbaclient.serveur.gererCompte narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof tpcorbaclient.serveur.gererCompte)
      return (tpcorbaclient.serveur.gererCompte)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      tpcorbaclient.serveur._gererCompteStub stub = new tpcorbaclient.serveur._gererCompteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static tpcorbaclient.serveur.gererCompte unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof tpcorbaclient.serveur.gererCompte)
      return (tpcorbaclient.serveur.gererCompte)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      tpcorbaclient.serveur._gererCompteStub stub = new tpcorbaclient.serveur._gererCompteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
