package tpcorbaclient.serveur;

/**
* serveur/gererCompteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from serveur.idl
* Friday, December 4, 2020 3:30:59 PM WAT
*/

public final class gererCompteHolder implements org.omg.CORBA.portable.Streamable
{
  public tpcorbaclient.serveur.gererCompte value = null;

  public gererCompteHolder ()
  {
  }

  public gererCompteHolder (tpcorbaclient.serveur.gererCompte initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = tpcorbaclient.serveur.gererCompteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    tpcorbaclient.serveur.gererCompteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tpcorbaclient.serveur.gererCompteHelper.type ();
  }

}
